title: "Alpha-One Demo Site"
description: "A responsive theme for Jekyll"
motto: "Enter any 11-digit prime number to continue."

url: "example.net" 
baseurl: ""

twitter_username: proudier
github_username:  proudier
linkedin_username: pierreroudier

header_link_1_label: Posts
header_link_1_href: posts.html
#header_link_2_label: Projects
#header_link_2_href: projects.html

favicon_png: favicon.png

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - alpha-one.gemspec
